# Generated by Django 5.2.14 on 2026-05-20 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('INVENTORY_RESERVED', 'Inventory Reserved'), ('PAYMENT_PROCESSING', 'Payment Processing'), ('COMPLETED', 'Completed'), ('PAYMENT_FAILED', 'Payment Failed'), ('CANCELLED', 'Cancelled'), ('OUT_OF_STOCK', 'Out of Stock')], db_index=True, default='PENDING', max_length=30),
        ),
    ]
